"""agregar contingency_event_id y emision_sin_json a facturas

Revision ID: 037ee9941b5d
Revises: bee29705505a
Create Date: 2026-06-15 19:35:28.836504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '037ee9941b5d'
down_revision: Union[str, Sequence[str], None] = 'bee29705505a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facturas', sa.Column('contingency_event_id', sa.UUID(), nullable=True))
    op.add_column('facturas', sa.Column('emision_sin_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_facturas_contingency_event_id'), 'facturas', ['contingency_event_id'], unique=False)
    op.create_foreign_key(None, 'facturas', 'contingency_events', ['contingency_event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'facturas', type_='foreignkey')
    op.drop_index(op.f('ix_facturas_contingency_event_id'), table_name='facturas')
    op.drop_column('facturas', 'emision_sin_json')
    op.drop_column('facturas', 'contingency_event_id')
    # ### end Alembic commands ###
