"""esquema inicial: tenants, sucursales, facturacion, billing

Revision ID: 5c193cc7c26f
Revises: 
Create Date: 2026-06-13 16:25:43.569128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c193cc7c26f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('precio_mensual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_por_factura', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('facturas_incluidas', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tenants',
    sa.Column('nit', sa.String(length=20), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('modalidad', sa.Enum('ELECTRONICA_EN_LINEA', 'COMPUTARIZADA_EN_LINEA', 'PORTAL_WEB', name='modalidad_facturacion'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_nit'), 'tenants', ['nit'], unique=True)
    op.create_table('actividades_economicas',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('codigo_caeb', sa.String(length=10), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actividades_economicas_tenant_id'), 'actividades_economicas', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('entidad', sa.String(length=100), nullable=False),
    sa.Column('entidad_id', sa.String(length=100), nullable=True),
    sa.Column('detalle', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('clientes',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nombre_razon_social', sa.String(length=255), nullable=False),
    sa.Column('numero_documento', sa.String(length=20), nullable=False),
    sa.Column('complemento', sa.String(length=10), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_tenant_id'), 'clientes', ['tenant_id'], unique=False)
    op.create_table('credentials',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('TOKEN_PROPIO', 'TOKEN_DELEGADO', 'CERTIFICADO_DIGITAL', name='tipo_credencial'), nullable=False),
    sa.Column('secret_ref', sa.String(length=255), nullable=False),
    sa.Column('vigente_desde', sa.String(length=20), nullable=True),
    sa.Column('vigente_hasta', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentials_tenant_id'), 'credentials', ['tenant_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVA', 'SUSPENDIDA', 'CANCELADA', name='estado_suscripcion'), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=False)
    op.create_table('sucursales',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('codigo_sucursal', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('direccion', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sucursales_tenant_id'), 'sucursales', ['tenant_id'], unique=False)
    op.create_table('webhook_endpoints',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('eventos', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('secret', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_endpoints_tenant_id'), 'webhook_endpoints', ['tenant_id'], unique=False)
    op.create_table('puntos_venta',
    sa.Column('sucursal_id', sa.UUID(), nullable=False),
    sa.Column('codigo_punto_venta', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_puntos_venta_sucursal_id'), 'puntos_venta', ['sucursal_id'], unique=False)
    op.create_table('contingency_events',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('punto_venta_id', sa.UUID(), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo', sa.String(length=500), nullable=False),
    sa.Column('resuelto', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['punto_venta_id'], ['puntos_venta.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contingency_events_tenant_id'), 'contingency_events', ['tenant_id'], unique=False)
    op.create_table('cufd_cache',
    sa.Column('punto_venta_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('vigente_desde', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vigente_hasta', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['punto_venta_id'], ['puntos_venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cufd_cache_punto_venta_id'), 'cufd_cache', ['punto_venta_id'], unique=False)
    op.create_table('dosificaciones',
    sa.Column('punto_venta_id', sa.UUID(), nullable=False),
    sa.Column('actividad_economica_id', sa.UUID(), nullable=False),
    sa.Column('tipo_documento_sector', sa.Integer(), nullable=False),
    sa.Column('numero_inicial', sa.Integer(), nullable=False),
    sa.Column('numero_final', sa.Integer(), nullable=False),
    sa.Column('numero_actual', sa.Integer(), nullable=False),
    sa.Column('clave_dosificacion_ref', sa.String(length=255), nullable=False),
    sa.Column('fecha_limite_emision', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actividad_economica_id'], ['actividades_economicas.id'], ),
    sa.ForeignKeyConstraint(['punto_venta_id'], ['puntos_venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dosificaciones_punto_venta_id'), 'dosificaciones', ['punto_venta_id'], unique=False)
    op.create_table('facturas',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('sucursal_id', sa.UUID(), nullable=False),
    sa.Column('punto_venta_id', sa.UUID(), nullable=False),
    sa.Column('dosificacion_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('numero_factura', sa.Integer(), nullable=False),
    sa.Column('cuf', sa.String(length=50), nullable=True),
    sa.Column('cufd', sa.String(length=100), nullable=True),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tipo_documento_sector', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'VALIDADA', 'CONTINGENCIA', 'RECHAZADA', 'ANULADA', name='estado_factura'), nullable=False),
    sa.Column('xml_path', sa.String(length=500), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['dosificacion_id'], ['dosificaciones.id'], ),
    sa.ForeignKeyConstraint(['punto_venta_id'], ['puntos_venta.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facturas_cuf'), 'facturas', ['cuf'], unique=True)
    op.create_index(op.f('ix_facturas_tenant_id'), 'facturas', ['tenant_id'], unique=False)
    op.create_table('factura_items',
    sa.Column('factura_id', sa.UUID(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factura_items_factura_id'), 'factura_items', ['factura_id'], unique=False)
    op.create_table('notas_credito_debito',
    sa.Column('factura_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('FACTURA', 'NOTA_CREDITO', 'NOTA_DEBITO', name='tipo_documento_fiscal'), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=False),
    sa.Column('monto', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cuf', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'VALIDADA', 'CONTINGENCIA', 'RECHAZADA', 'ANULADA', name='estado_nota'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notas_credito_debito_cuf'), 'notas_credito_debito', ['cuf'], unique=True)
    op.create_index(op.f('ix_notas_credito_debito_factura_id'), 'notas_credito_debito', ['factura_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('factura_id', sa.UUID(), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('monto_cobrado', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('facturado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factura_id')
    )
    op.create_index(op.f('ix_usage_records_tenant_id'), 'usage_records', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_records_tenant_id'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_notas_credito_debito_factura_id'), table_name='notas_credito_debito')
    op.drop_index(op.f('ix_notas_credito_debito_cuf'), table_name='notas_credito_debito')
    op.drop_table('notas_credito_debito')
    op.drop_index(op.f('ix_factura_items_factura_id'), table_name='factura_items')
    op.drop_table('factura_items')
    op.drop_index(op.f('ix_facturas_tenant_id'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_cuf'), table_name='facturas')
    op.drop_table('facturas')
    op.drop_index(op.f('ix_dosificaciones_punto_venta_id'), table_name='dosificaciones')
    op.drop_table('dosificaciones')
    op.drop_index(op.f('ix_cufd_cache_punto_venta_id'), table_name='cufd_cache')
    op.drop_table('cufd_cache')
    op.drop_index(op.f('ix_contingency_events_tenant_id'), table_name='contingency_events')
    op.drop_table('contingency_events')
    op.drop_index(op.f('ix_puntos_venta_sucursal_id'), table_name='puntos_venta')
    op.drop_table('puntos_venta')
    op.drop_index(op.f('ix_webhook_endpoints_tenant_id'), table_name='webhook_endpoints')
    op.drop_table('webhook_endpoints')
    op.drop_index(op.f('ix_sucursales_tenant_id'), table_name='sucursales')
    op.drop_table('sucursales')
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_credentials_tenant_id'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_clientes_tenant_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_actividades_economicas_tenant_id'), table_name='actividades_economicas')
    op.drop_table('actividades_economicas')
    op.drop_index(op.f('ix_tenants_nit'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_table('plans')
    # ### end Alembic commands ###
