"""agregar tabla api_keys

Revision ID: bee29705505a
Revises: 2d913fb54643
Create Date: 2026-06-15 19:26:24.176615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bee29705505a'
down_revision: Union[str, Sequence[str], None] = '2d913fb54643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('prefijo', sa.String(length=12), nullable=False),
    sa.Column('clave_hash', sa.String(length=64), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_uso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_keys_clave_hash', 'api_keys', ['clave_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_index('ix_api_keys_clave_hash', table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
