"""agregar numero_nota codigo_documento_sector cufd a notas_credito_debito

Revision ID: d56e0b94c900
Revises: 037ee9941b5d
Create Date: 2026-06-15 21:36:16.392308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd56e0b94c900'
down_revision: Union[str, Sequence[str], None] = '037ee9941b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notas_credito_debito', sa.Column('numero_nota', sa.Integer(), nullable=False))
    op.add_column('notas_credito_debito', sa.Column('codigo_documento_sector', sa.Integer(), nullable=False))
    op.add_column('notas_credito_debito', sa.Column('cufd', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notas_credito_debito', 'cufd')
    op.drop_column('notas_credito_debito', 'codigo_documento_sector')
    op.drop_column('notas_credito_debito', 'numero_nota')
    # ### end Alembic commands ###
